### ISSUE TITLE
Relax Group Dependencies

### ISSUE THREAD

**Issue by KyleKing** [madkinsz/poetry-relax#6]
In local testing, it looks like `poetry relax` isn't relaxing group dependencies. For example:

```sh
> poetry add antigravity --group=xkcd
Using version ^0.1 for antigravity
...
> poetry relax
Checking dependencies for relaxable constraints...
No dependency constraints to relax.
> tail -n 2 pyproject.toml
[tool.poetry.group.xkcd.dependencies]
antigravity = "^0.1"
```

Thanks for building this package!

**Comment by madkinsz** [comment]
Hey @KyleKing we default to the `main` group (ref https://github.com/madkinsz/poetry-relax/blob/bf497bc0d663d55a7780133d1bcd986e9502aa8d/src/poetry_relax/command.py#L30-L36) to match Poetry's behavior. If you specify a group e.g. `poetry relax --group xkcd` does it work for you?
