### ISSUE TITLE
Support all groups at once

### ISSUE THREAD

**Issue by woutervh** [madkinsz/poetry-relax#7]
I recently started to refactor my project.toml-files into multiple groups like this

```
[tool.poetry.group.dev.dependencies]
bandit = { extras = ["toml"], version = ">=1.7.4" }
black = ">=22.1.0"
flake8 = ">=4.0.1"
flake8-pyproject = ">=1.2.2"
ipdb = ">=0.13.9"
isort = ">=5.10.1"
pre-commit = ">=2.14.1"
pre-commit-hooks = ">=4.1.0"
pylint = ">=2.12.2"

[tool.poetry.group.deploy.dependencies]
supervisor = ">=4.2.4"
gunicorn = ">=20.1.0"
uvicorn = ">=0.21.1"

[tool.poetry.group.docs.dependencies]
autoapi = ">=2.0.1"
recommonmark = ">=0.7.1"
Sphinx = ">=4.4.0"
sphinx-autoapi = ">=1.8.4"
sphinx-markdown-tables = ">=0.0.17"
sphinx-rtd-theme = { version = ">=1.2.0rc3", allow-prereleases = true }

[tool.poetry.group.test.dependencies]
pytest = ">=7.0.1"
pytest-cov = ">=3.0.0"
pytest-freezegun = ">=0.4.2"
pytest-mock = ">=3.10.0"

[tool.poetry.group.typing.dependencies]
mypy = ">=0.931"
types-cachetools = ">=5.3.0.4"
types-python-dateutil = ">=2.8.19"
types-requests = ">=2.28.9"

```

I basically don't care about what group needs relaxing, because they ALL need relaxing.

For the moment I need to execute:
```
poetry relax --group=main
poetry relax --group=deploy
poetry relax --group=docs
poetry relax --group=test
poetry relax --group=typing


```

**Comment by madkinsz** [comment]
Hey @WouterVH glad to hear this has been useful to you.

Does Poetry provide a mechanism to act on multiple groups at once? I'd like to try to match their API if feasible. Otherwise yeah it totally seems convenient to be able to relax all groups in one-shot.

**Comment by madkinsz** [comment]
@WouterVH oh I just meant in their CLI so we could match the flag they use.

Looking into the code I wrote here, everything is written to work on a single group at a time. I can look into this feature, but it's not a quick change.
